### ISSUE TITLE
Error creating tags

### ISSUE THREAD

**Issue by a-m-s** [LucHermitte/lh-tags#2]
I installed the two plugins using Vundle, setup `b:tags_dirname` opened a suitable file, and then typed `C-Xta`, and this happened:

```
Error detected while processing function lh#tags#update_all[1]..lh#tags#run[18]..<SNR>72_UpdateTags_for_All[6]..lh#os#sys_cd[1]..<SNR>73_SystemCmd:
line    2:
E121: Undefined variable: s:cd
E15: Invalid expression: s:{a:cmdName}

```

Did I miss something?

**Comment by LucHermitte** [comment]
You didn't miss anything.
I did.
Let me know if this patch to lh-vim-lib fixes the issue on your side.

**Comment by a-m-s** [comment]
Yes, that seems to have done the trick.

Thanks a lot.

**Comment by LucHermitte** [comment]
Thank you
